version: 2.1

executors:
    pt:
        working_directory: ~/pt
        parameters:
            resource_class:
                type: string
                default: medium
        docker:
            - image: cimg/node:16.13.0
              auth:
                  username: $DOCKER_HUB_USERNAME
                  password: $DOCKER_HUB_TOKEN

commands:
    yarn_install:
        description: Install NPM dependencies
        steps:
            - run:
                  name: yarn install
                  command: yarn install --frozen-lockfile --non-interactive

jobs:
  publish:
    executor: pt
    steps:
      - checkout
      - yarn_install
      - run:
          name: System information
          command: |
            echo "Node.js $(node -v)"
            echo "npm $(npm -v)"
            echo "Yarn v$(yarn --version)"
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: yarn publish --access public

workflows:
    version: 2
    default_workflow:
        jobs:
            -   publish:
                    context:
                        - docker-hub
                    filters:
                        branches:
                            ignore: /.*/
                        tags:
                            only: /^\d+(?:\.\d+)*$/
