version: 2.1

var_1: &cache_key package-cache-{{ checksum "yarn.lock" }}
# Restores the cache that could be available for the current Yarn lock file.
var_2: &restore_cache
    restore_cache:
        key: *cache_key

executors:
    pt:
        working_directory: ~/pt
        parameters:
            resource_class:
                type: string
                default: medium
        docker:
            - image: cimg/node:16.13.0
              auth:
                  username: $DOCKER_HUB_USERNAME
                  password: $DOCKER_HUB_TOKEN

commands:
    yarn_install:
        description: Install NPM dependencies
        steps:
            - run:
                  name: yarn install
                  command: yarn install --frozen-lockfile --non-interactive

jobs:
    install:
        executor: mosaic
        steps:
            - checkout
            - *restore_cache
            - yarn_install
            - save_cache:
                key: *cache_key
                paths:
                    - ~/.cache/yarn
                    - node_modules
            - persist_to_workspace:
                    root: ~/pt
                    paths:
                        - .
    publish:
        executor: pt
        steps:
          - *restore_cache
          - prepare_job
          - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          - run: npm publish --access public

workflows:
    version: 2
    default_workflow:
        jobs:

           - install

           - publish:
                requires:
                    - install
                context:
                    - docker-hub
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^\d+(?:\.\d+)*$/
